name: test-build-deploy

on:
  pull_request:
    # paths: ["src/**"]

jobs:
  test-build-deploy:
    name: Application test build & deploy
    runs-on: ubuntu-latest

    # services:
    #   redis:
    #     image: redis
    #     ports:
    #       - "6379:6379"

    #   postgres:
    #     image: postgres:15.0
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: relayer
    #       POSTGRES_DB: service-relayer
    #     ports:
    #       - "5432:5432"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"

      - name: Install
        run: npm i

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
